export enum TaxTypeEnum {
  // EMPLOYEE
  HEALTH_INSURANCE_PAID_EMPLOYEE = 'TAX_TYPE.HEALTH_INSURANCE_PAID_EMPLOYEE',
  SOCIAL_INSURANCE_PAID_EMPLOYEE = 'TAX_TYPE.SOCIAL_INSURANCE_PAID_EMPLOYEE',
  PERSONAL_INCOME_TAX = 'TAX_TYPE.PERSONAL_INCOME_TAX',
  TAX_CREDITS = 'TAX_TYPE.TAX_CREDITS',
  TAX_BENEFITS = 'TAX_TYPE.TAX_BENEFITS',

  TOTAL_COST_FOR_EMPLOYER = 'TAX_TYPE.TOTAL_COST_FOR_EMPLOYER',
  HEALTH_INSURANCE_PAID_EMPLOYER = 'TAX_TYPE.HEALTH_INSURANCE_PAID_EMPLOYER',
  SOCIAL_INSURANCE_PAID_EMPLOYER = 'TAX_TYPE.SOCIAL_INSURANCE_PAID_EMPLOYER',
}
