export enum TaxTypeEnum {
  // EMPLOYEE
  HEALTH_INSURANCE_PAID_EMPLOYEE = 'TAX_TYPE.HEALTH_INSURANCE_PAID_EMPLOYEE',
  SOCIAL_INSURANCE_PAID_EMPLOYEE = 'TAX_TYPE.SOCIAL_INSURANCE_PAID_EMPLOYEE',
  PERSONAL_INCOME_TAX = 'TAX_TYPE.PERSONAL_INCOME_TAX',
  TAX_CREDITS = 'TAX_TYPE.TAX_CREDITS',
  TAX_BENEFITS = 'TAX_TYPE.TAX_BENEFITS',

  // PAYROLL_COSTS = 'TAX_TYPE.PAYROLL_COSTS',
  // HEALTH_INSURANCE_PAID_EMPLOYER = 'TAX_TYPE.HEALTH_INSURANCE_PAID_EMPLOYER',
  // SOCIAL_INSURANCE_PAID_EMPLOYER = 'TAX_TYPE.SOCIAL_INSURANCE_PAID_EMPLOYER',
  // TAX_TOTAL_WAGES_EMPLOYER = 'TAX_TYPE.TAX_TOTAL_WAGES_EMPLOYER',
  // TAX_PERSONAL_INCOME = 'TAX_TYPE.TAX_PERSONAL_INCOME',
  // ADVANCE_TAX_PERSONAL_INCOME = 'TAX_TYPE.ADVANCE_TAX_PERSONAL_INCOME',
  // TAX_BONUS = 'TAX_TYPE.TAX_BONUS',
  // TOTAL_PAID_TO_STATE = 'TAX_TYPE.TOTAL_PAID_TO_STATE',
}
