// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  appName: 'Czech Salary',
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.exchangeratesapi.io/',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    { name: 'CZECH', code: 'cs-CZ', icon: 'https://img.icons8.com/office/16/000000/czech-republic.png' },
    { name: 'ENGLISH', code: 'en-US', icon: 'https://img.icons8.com/office/16/000000/great-britain.png' },
  ],
};
